image:
  - Visual Studio 2017
  - Ubuntu

# Only effective for Ubuntu image
stack: node 10

environment:
  CODACY_PROJECT_TOKEN:
    secure: 6eKx+VYCDy8aPfSrBCsztPZHSzsPwvtYi5p7dCB9wb0dHoN9paQ3PlEa3CjC0nwi

install:
  # Node version for VS2017 image
  - ps: if ($isWindows) { Install-Product node 10 x64 }
  - npm install

before_build:
  - node --version
  - npm --version
  - npx --version

build_script:
  - npm run release
  - cmd: npx pkg -t node10-win-x64 -o dist/dekinai.exe dekinai.min.js
  - cmd: copy node_modules\better-sqlite3\build\Release\better_sqlite3.node dist
  - sh: npx pkg -t node10-linux-x64 -o dist/dekinai dekinai.min.js
  - sh: cp node_modules/better-sqlite3/build/Release/better_sqlite3.node dist
  - ps: New-Item -ItemType directory -Path dist\app,dist\template,dist\uploads
  - ps: Copy-Item template\config.json -Destination dist
  - ps: Copy-Item template\dekinai.sxcu -Destination dist\template

after_build:
  - 7z a dekinai.zip ./dist/*

test_script:
  - cmd: npm run codacy
  - sh: npm test

artifacts:
  - path: dekinai.zip
    name: Dekinai
